name: $(GITVERSION_FullSemVer)
trigger:
 batch: true
 branches:
  include:
    - master
pr: none
pool:
  vmImage: 'windows-latest'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
stages:
  - stage: BuildAndTest
    displayName: Build and test
    jobs:
    - template: templates/include-build-and-test-steps.yml
  - stage: TestGitVersionStage
    displayName: Temporary stage to test variable access
    jobs:
      - job: TestGitVersionJob
        displayName: Temporary job to test variable access
        steps: 
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'
          - task: gitversion/execute@0
            displayName: Execute GitVersion
            inputs:
              useConfigFile: true
              configFilePath: '$(Build.SourcesDirectory)\GitVersion.yml'
  - stage: TestGitVersionVariableAccessStage
    displayName: Temporary stage to test variable access
    jobs:
      - job: TestGitVersionVariableAccessJob
        displayName: Temporary job to test variable access
        steps: 
          - task: CmdLine@2
            inputs:
              script: 'echo $(GitVersion.SemVer)'
  - stage: Publish
    displayName: Publish
    jobs:
      - job: PublishJob
        displayName: Publish 
        steps:
          - checkout: none
          - download: current
            displayName: Download NuGet package artifact
            artifact: Capgemini.PowerApps.SpecFlowBindings
          - task: NuGetCommand@2
            displayName: Push to NuGet.org
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/Capgemini.PowerApps.SpecFlowBindings/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: Capgemini_UK
          - task: GitHubRelease@1
            displayName: Create GitHub releaes
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              gitHubConnection: 'GitHub (ewingjm)'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(GITVERSION_FullSemVer)'
              releaseNotesSource: 'inline'
              assets: '$(Pipeline.Workspace)/Capgemini.PowerApps.SpecFlowBindings/*'
              isPreRelease: true
              changeLogCompareToRelease: lastNonDraftRelease
              changeLogType: commitBased