name: $(GITVERSION_FullSemVer)
trigger: none
pr:
  - master
pool:
  vmImage: 'windows-latest'
stages:
  - stage: Build
    jobs:
    - job: BuildJob
      displayName: Build
      steps:
        - template: templates/include-build-and-test-steps.yml