name: $(GITVERSION_FullSemVer)
trigger:
 batch: true
 branches:
  include:
    - master
pr: none
pool:
  vmImage: 'windows-latest'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
stages:
  - stage: TestGitVersionStage
    displayName: Temporary stage to test variable access
    jobs:
      - job: TestGitVersionJob
        displayName: Temporary job to test variable access
        variables:
          GitVersion.SemVer: ''
        steps: 
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'
          - task: gitversion/execute@0
            displayName: Execute GitVersion
            inputs:
              useConfigFile: true
              configFilePath: '$(Build.SourcesDirectory)\GitVersion.yml'
          - pwsh: Write-Host "Setting output variable as $(GitVersion.SemVer)"
          - pwsh: Write-Host "##vso[task.setvariable variable=GitVersionSemVer;isOutput=true]$(GitVersion.SemVer)"
            name: SetGitVersionTask
  - stage: TestGitVersionVariableAccessStage
    displayName: Temporary stage to test variable access
    jobs:
      - job: TestGitVersionVariableAccessJob
        variables: 
          GitVersion.SemVer: $[stageDependencies.TestGitVersionStage.outputs['TestGitVersionJob.SetGitVersionTask.GitVersionSemVer']]
        displayName: Temporary job to test variable access
        steps: 
          - task: CmdLine@2
            inputs:
              script: echo $(GitVersion.SemVer)