name: $(GITVERSION_FullSemVer)

trigger:
 batch: true
 branches:
  include:
    - master

pr: none

pool:
  vmImage: windows-latest
stages:
  - template: templates/build-and-test-stages.yml      
  - stage: Publish
    displayName: Publish
    jobs:
      - job: PublishJob
        displayName: Publish 
        variables: 
          SemVer: $[ stageDependencies.BuildAndTest.BuildAndTestJob.outputs['OutputSemVerTask.SemVer'] ]
        steps:
          - checkout: none
          - download: current
            displayName: Download NuGet package artifact
            artifact: Capgemini.PowerApps.SpecFlowBindings
          - task: NuGetCommand@2
            displayName: Push to NuGet.org
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/Capgemini.PowerApps.SpecFlowBindings/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: Capgemini_UK
          - task: GitHubRelease@1
            displayName: Create GitHub releaes
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              gitHubConnection: 'GitHub (ewingjm)'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(SemVer)'
              releaseNotesSource: 'inline'
              assets: '$(Pipeline.Workspace)/Capgemini.PowerApps.SpecFlowBindings/*'
              isPreRelease: true
              changeLogCompareToRelease: 'lastNonDraftRelease'
              changeLogType: commitBased
