trigger:
 batch: true
 branches:
  include:
    - master
pr: none
pool:
  vmImage: 'windows-latest'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publish: 'true'
stages:
  - stage: Build
    jobs:
    - job: BuildJob
      displayName: Build
      steps:
        - task: NuGetToolInstaller@1
          displayName: Install NuGet
        - task: NuGetCommand@2
          displayName: Restore NuGet packages
          inputs:
            restoreSolution: '$(solution)'
        - task: Npm@1
          displayName: Restore npm packages
          inputs:
            verbose: false
            workingDir: driver
        - task: VSBuild@1
          displayName: Build solution
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: NuGetCommand@2
          displayName: Pack NuGet package
          inputs:
            command: pack
            packagesToPack: bindings\src\Capgemini.PowerApps.SpecFlowBindings\Capgemini.PowerApps.SpecFlowBindings.csproj
            includeReferencedProjects: true
            packDestination: '$(Build.ArtifactStagingDirectory)/out'
            configuration: $(buildConfiguration) 
        - publish: $(Build.ArtifactStagingDirectory)/out
          displayName: Publish NuGet artifact
          artifact: Capgemini.PowerApps.SpecFlowBindings
        - publish: driver
          displayName: Publish driver
          artifact: driver
        - publish: bindings\tests\Capgemini.PowerApps.SpecFlowBindings.UiTests\bin\$(buildConfiguration)
          displayName: Publish tests
          artifact: tests
  - stage: UiTest
    displayName: UI Test
    dependsOn: Build
    jobs:
    - job: UiTestJob
      displayName: UI Test
      variables:
        - group: Cap Dev - CI
      steps:
        - checkout: none
        - download: current
          displayName: Download tests
          artifact: tests
        - task: VSTest@2
          displayName: Run tests
          inputs:
            uiTests: true
            runInParallel: true
            testAssemblyVer2: |
              **\*UiTests.dll
              !**\*TestAdapter.dll
              !**\obj\**
            searchFolder: $(Pipeline.Workspace)\tests
          continueOnError: true
          env:
            POWERAPPS_SPECFLOW_BINDINGS_TEST_ADMIN_USERNAME: $(User ADO Integration Username)
            POWERAPPS_SPECFLOW_BINDINGS_TEST_ADMIN_PASSWORD: $(User ADO Integration Password)
            POWERAPPS_SPECFLOW_BINDINGS_TEST_URL: $(URL)